#Solana RPC
SOLANA:
  #If the LP node has below this amount it will stop processing new swaps
  MIN_NATIVE_RESERVE: 0.1
  #Solana RPC URL to use, it is recommended to use a dedicated RPC endpoint from e.g. Helius (recommended), Quicknode, etc.
  RPC_URL: "https://api.devnet.solana.com"
  #Maximum fee in micro lamport/CU to use for transactions
  MAX_FEE_MICRO_LAMPORTS: 250000
  #File with the wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
  #Static tip (in lamports) to add to every transaction
  # STATIC_TIP: 50000

#Starknet RPC
#STARKNET:
#  #If the LP node has below this amount it will stop processing new swaps
#  MIN_NATIVE_RESERVE: 100
#  #Starknet RPC URL
#  RPC_URL: ""
#  #Can also optionally specify an additional WS URL - allows for faster swap processing
#  #WS_URL: ""
#  #Gas price limits (higher bound)
#  MAX_L1_FEE_GWEI: 20000000
#  MAX_L2_FEE_GWEI: 4000000
#  MAX_L1_DATA_FEE_GWEI: 10000000
#  #Starknet chain
#  CHAIN: "SEPOLIA"
#
#  #File with wallet mnemonic seed
#  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
#
#  #Starknet quotes timeout
#  AUTHORIZATION_TIMEOUT: 60

#Botanix RPC
BOTANIX:
  #If the LP node has below this amount it will stop processing new swaps
  MIN_NATIVE_RESERVE: 0.0002
  #Botanix RPC URL, can either be an http or ws RPC
  RPC_URL: "https://node.botanixlabs.dev"
  #Maximum block range that the underlying RPC provider supports
  MAX_LOGS_BLOCK_RANGE: 900
  #Fees
  MAX_FEE_GWEI: 2
  FEE_TIP_GWEI: 0.001
  #Botanix chain
  CHAIN: "TESTNET"

  #File with wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

  #Botanix quotes timeout
  AUTHORIZATION_TIMEOUT: 60

#Alpen RPC
ALPEN:
  #If the LP node has below this amount it will stop processing new swaps
  MIN_NATIVE_RESERVE: 0.0002
  #Alpen RPC URL, can either be an http or ws RPC
  RPC_URL: "https://rpc.testnet.alpenlabs.io"
  #Maximum block range that the underlying RPC provider supports
  MAX_LOGS_BLOCK_RANGE: 900
  #Fees
  MAX_FEE_GWEI: 2
  FEE_TIP_GWEI: 0.001
  #Alpen chain
  CHAIN: "TESTNET"

  #File with wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

  #Botanix quotes timeout
  AUTHORIZATION_TIMEOUT: 60

#GOAT network RPC
GOAT:
  #If the LP node has below this amount it will stop processing new swaps
  MIN_NATIVE_RESERVE: 0.0002
  #GOAT Network RPC URL, can either be an http or ws RPC
  RPC_URL: "https://rpc.testnet3.goat.network"
  #Maximum block range that the underlying RPC provider supports
  MAX_LOGS_BLOCK_RANGE: 900
  #Fees
  MAX_FEE_GWEI: 2
  #Has to be at least 0.005 for GOAT Network!
  FEE_TIP_GWEI: 0.005
  #GOAT chain
  CHAIN: "TESTNET"

  #File with wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

  #Botanix quotes timeout
  AUTHORIZATION_TIMEOUT: 60

#Required APY option premium to be paid by the users as security deposit with BTC -> Solana swaps
SECURITY_DEPOSIT_APY: 20

#Bitcoin RPC configuration
BITCOIND:
  PROTOCOL: "http"
  PORT: 18332
  HOST: "bitcoind-testnet"
  RPC_USERNAME: "user1"
  RPC_PASSWORD: "ThisIsAPassword"
  NETWORK: "testnet"

#LND RPC configuration
LND:
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
  WALLET_PASSWORD_FILE: "/mnt/share/wallet/password.txt"
  CERT_FILE: "/mnt/share/lnd/tls.cert"
  MACAROON_FILE: "/mnt/share/lnd/admin.macaroon"
  HOST: "lnd-testnet"
  PORT: 20009

#LN setup, uncomment these lines if you want to enable lightning network support for your node
#LN:
#  #Total swap fee is calculated as BASE_FEE + {SWAP_VALUE}*FEE_PERCENTAGE
#  #Base fee (in BTC) to be paid by every swap
#  BASE_FEE: 0.00000010
#  #Fee (in %) to be charged on the swaps
#  FEE_PERCENTAGE: 0.3
#
#  #Minimum swappable amount in BTC (for lightning network swaps)
#  MIN: 0.00001000
#  #Maximum swappable amount in BTC (for lightning network swaps)
#  MAX: 0.01000000
#
#  #Allow lightning network swaps that cannot be probed first
#  ALLOW_NON_PROBABLE_SWAPS: true
#  #Allow lightning network swaps where the LN invoice has a very short expiry
#  ALLOW_LN_SHORT_EXPIRY: true
#  #Set expiration for lightning swaps invoices
#  INVOICE_EXPIRY_SECONDS: 90
#
#  #Maximum amounts for swap for gas
#  GAS_MAX:
#    STARKNET: 5
#    SOLANA: 0.03
#    BOTANIX: 0.00005
#    ALPEN: 0.00005
#    GOAT: 0.00005
#
#  MAX_INFLIGHT_SWAPS: 100
#  MAX_INFLIGHT_AUTO_SWAPS: 20

#On-chain setup
ONCHAIN:
  #Total swap fee is calculated as BASE_FEE + {SWAP_VALUE}*FEE_PERCENTAGE
  #Base fee (in BTC) to be paid by every swap
  BASE_FEE: 0.00000100
  #Fee (in %) to be charged on the swaps
  FEE_PERCENTAGE: 0.25

  #Minimum swappable amount in BTC (for on-chain swaps)
  MIN: 0.00010000
  #Maximum swappable amount in BTC (for on-chain swaps)
  MAX: 0.05000000

  #Network fee buffer (in %), we charge the client this much more on the network
  # fee to accomodate for the possible fee rate increases in the near future 
  NETWORK_FEE_ADD_PERCENTAGE: 25

  #Additional fee to pay, above the estimated sats/vB fee
  ADD_NETWORK_FEE: 5

  MAX_INFLIGHT_SWAPS: 100

#On-chain setup BTC -> Starknet/EVM (new protocol - not BTC -> Solana!!!)
ONCHAIN_SPV:
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

  #Total swap fee is calculated as BASE_FEE + {SWAP_VALUE}*FEE_PERCENTAGE
  #Base fee (in BTC) to be paid by every swap
  BASE_FEE: 0.00000150
  #Fee (in %) to be charged on the swaps
  FEE_PERCENTAGE: 0.3

  #Minimum swappable amount in BTC (for on-chain swaps)
  MIN: 0.00010000
  #Maximum swappable amount in BTC (for on-chain swaps)
  MAX: 0.05000000

  #Maximum "gas drop" for different chains
  GAS_MAX:
    STARKNET: 5
    SOLANA: 0.05
    BOTANIX: 0.00005
    ALPEN: 0.00005
    GOAT: 0.00005

  MAX_INFLIGHT_SWAPS: 100

#Tradable assets setup
ASSETS:
  ABTC:
    chains:
      ALPEN:
        address: "0x0000000000000000000000000000000000000000"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "$fixed-100000000"
  BBTC:
    chains:
      BOTANIX:
        address: "0x0000000000000000000000000000000000000000"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "$fixed-100000000"
  GBTC:
    chains:
      GOAT:
        address: "0x0000000000000000000000000000000000000000"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "$fixed-100000000"
  SOL:
    chains:
      SOLANA:
        address: "So11111111111111111111111111111111111111112"
        decimals: 9
        securityDepositAllowed: true
    pricing: "SOLBTC"
  ETH:
    chains:
      STARKNET:
        address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "ETHBTC"
  STRK:
    chains:
      STARKNET:
        address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "STRKUSDT;!BTCUSDT"

#CLI - command line interface config
CLI:
  #CLI bind address
  ADDRESS: "0.0.0.0"
  #CLI TCP port
  PORT: 40121

#REST RFQ API config
REST:
  #REST API bind address
  ADDRESS: "0.0.0.0"
  #REST API port
  PORT: 8443

#Automatic SSL certificate provisioning config
SSL_AUTO:
  #HTTP listen port to list for ACME challenges
  HTTP_LISTEN_PORT: 80
  #DNS proxy to use - mapping the server's IP address to a domain
  DNS_PROXY: "nodes.atomiq.exchange"

#Node extensions/plugins
PLUGINS:
  atomiq-archiver: "atomiq-archiver@latest"
