BTC_PROTOCOL: "http"
BTC_PORT: 8332
ZMQ_PORT: 39332
BTC_HOST: "bitcoind"
BTC_RPC_USERNAME: "user1"
BTC_RPC_PASSWORD: "ThisIsAPassword"

#Solana config
SOLANA:
  #Solana RPC URL to use, it is recommended to use a dedicated RPC endpoint from e.g. Helius (recommended), Quicknode, etc.
  RPC_URL: "https://api.mainnet-beta.solana.com"
  #CLI - command line interface config
  CLI_ADDRESS: "0.0.0.0"
  CLI_PORT: 40220
  #File with the wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
  #Fee settings
  MAX_FEE_MICRO_LAMPORTS: 250000
  STATIC_TIP: "10000"
  #Jito transaction relayer configuration
  JITO:
    PUBKEY: "DttWaMuVvTiduZRnguLF7jNxTgiMBZ1hyAumKUiL2KRL"
    ENDPOINT: "https://frankfurt.mainnet.block-engine.jito.wtf/api/v1/transactions"

STARKNET:
  #Starknet RPC URL to use, it is recommended to use a dedicated RPC endpoint
  RPC_URL: "https://starknet-mainnet.public.blastapi.io/rpc/v0_8"
  #CLI - command line interface config
  CLI_ADDRESS: "0.0.0.0"
  CLI_PORT: 40230
  #Maximum gas price
  MAX_L1_FEE_GWEI: 20000000
  MAX_L2_FEE_GWEI: 4000000
  MAX_L1_DATA_FEE_GWEI: 10000000
  #Starknet chain to use
  CHAIN: "MAIN"
  #File with the wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
