#GOAT network RPC
GOAT:
  #If the LP node has below this amount it will stop processing new swaps
  MIN_NATIVE_RESERVE: 0.0002
  #GOAT Network RPC URL, can either be an http or ws RPC
  RPC_URL: "https://rpc.testnet3.goat.network"
  #Maximum block range that the underlying RPC provider supports
  MAX_LOGS_BLOCK_RANGE: 900
  #Fees
  MAX_FEE_GWEI: 2
  #Has to be at least 0.005 for GOAT Network!
  FEE_TIP_GWEI: 0.005
  #GOAT chain
  CHAIN: "TESTNET"

  #File with wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

  #Botanix quotes timeout
  AUTHORIZATION_TIMEOUT: 60

#Required APY option premium to be paid by the users as security deposit with BTC -> Solana swaps
SECURITY_DEPOSIT_APY: 20

#Bitcoin RPC configuration
BITCOIND:
  PROTOCOL: "http"
  PORT: 18332
  HOST: "bitcoind-testnet4"
  RPC_USERNAME: "user1"
  RPC_PASSWORD: "ThisIsAPassword"
  NETWORK: "testnet4"

#LND RPC configuration
LND:
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
  WALLET_PASSWORD_FILE: "/mnt/share/wallet/password.txt"
  CERT_FILE: "/mnt/share/lnd/tls.cert"
  MACAROON_FILE: "/mnt/share/lnd/admin.macaroon"
  HOST: "lnd-testnet4"
  PORT: 20009

#LN setup, uncomment these lines if you want to enable lightning network support for your node
#LN:
#  #Total swap fee is calculated as BASE_FEE + {SWAP_VALUE}*FEE_PERCENTAGE
#  #Base fee (in BTC) to be paid by every swap
#  BASE_FEE: 0.00000010
#  #Fee (in %) to be charged on the swaps
#  FEE_PERCENTAGE: 0.3
#
#  #Minimum swappable amount in BTC (for lightning network swaps)
#  MIN: 0.00001000
#  #Maximum swappable amount in BTC (for lightning network swaps)
#  MAX: 0.01000000
#
#  #Allow lightning network swaps that cannot be probed first
#  ALLOW_NON_PROBABLE_SWAPS: true
#  #Allow lightning network swaps where the LN invoice has a very short expiry
#  ALLOW_LN_SHORT_EXPIRY: true
#  #Set expiration for lightning swaps invoices
#  INVOICE_EXPIRY_SECONDS: 90
#
#  #Maximum amounts for swap for gas
#  GAS_MAX:
#    STARKNET: 5
#    CITREA: 0.0001
#
#  MAX_INFLIGHT_SWAPS: 100
#  MAX_INFLIGHT_AUTO_SWAPS: 20

#On-chain setup
ONCHAIN:
  #Total swap fee is calculated as BASE_FEE + {SWAP_VALUE}*FEE_PERCENTAGE
  #Base fee (in BTC) to be paid by every swap
  BASE_FEE: 0.00000100
  #Fee (in %) to be charged on the swaps
  FEE_PERCENTAGE: 0.25

  #Minimum swappable amount in BTC (for on-chain swaps)
  MIN: 0.00010000
  #Maximum swappable amount in BTC (for on-chain swaps)
  MAX: 0.05000000

  #Network fee buffer (in %), we charge the client this much more on the network
  # fee to accomodate for the possible fee rate increases in the near future 
  NETWORK_FEE_ADD_PERCENTAGE: 25

  #Additional fee to pay, above the estimated sats/vB fee
  ADD_NETWORK_FEE: 5

  MAX_INFLIGHT_SWAPS: 100

#On-chain setup BTC -> Starknet/EVM (new protocol - not BTC -> Solana!!!)
ONCHAIN_SPV:
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

  #Total swap fee is calculated as BASE_FEE + {SWAP_VALUE}*FEE_PERCENTAGE
  #Base fee (in BTC) to be paid by every swap
  BASE_FEE: 0.00000150
  #Fee (in %) to be charged on the swaps
  FEE_PERCENTAGE: 0.3

  #Minimum swappable amount in BTC (for on-chain swaps)
  MIN: 0.00010000
  #Maximum swappable amount in BTC (for on-chain swaps)
  MAX: 0.05000000

  #Maximum "gas drop" for different chains
  GAS_MAX:
    STARKNET: 5
    CITREA: 0.0001

  MAX_INFLIGHT_SWAPS: 100

#Tradable assets setup
ASSETS:
  GBTC:
    chains:
      GOAT:
        address: "0x0000000000000000000000000000000000000000"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "$fixed-100000000"
  PegBTC:
    chains:
      GOAT:
        address: "0x42Dff13a9D6C33f89311C188F6eA780D00287F17"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "$fixed-100000000"

#CLI - command line interface config
CLI:
  #CLI bind address
  ADDRESS: "0.0.0.0"
  #CLI TCP port
  PORT: 40121

#REST RFQ API config
REST:
  #REST API bind address
  ADDRESS: "0.0.0.0"
  #REST API port
  PORT: 8443

#Automatic SSL certificate provisioning config
SSL_AUTO:
  #HTTP listen port to list for ACME challenges
  HTTP_LISTEN_PORT: 80
  #DNS proxy to use - mapping the server's IP address to a domain
  DNS_PROXY: "nodes.atomiq.exchange"

#Node extensions/plugins
PLUGINS:
  atomiq-archiver: "atomiq-archiver@latest"
