#Bitcoin RPC configuration
BTC_PROTOCOL: "http"
BTC_PORT: 18332
ZMQ_PORT: 49332
BTC_HOST: "bitcoind-testnet"
BTC_RPC_USERNAME: "user1"
BTC_RPC_PASSWORD: "ThisIsAPassword"

#Solana config
SOLANA:
  #Solana RPC URL to use, it is recommended to use a dedicated RPC endpoint from e.g. Helius (recommended), Quicknode, etc.
  RPC_URL: "https://api.devnet.solana.com"
  #CLI - command line interface config
  CLI_ADDRESS: "0.0.0.0"
  CLI_PORT: 40120
  #Fee settings
  MAX_FEE_MICRO_LAMPORTS: 250000
  STATIC_TIP: "10000"
  #File with the wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

#STARKNET:
#  #Starknet RPC URL to use, it is recommended to use a dedicated RPC endpoint
#  RPC_URL: ""
#  #Can also optionally specify an additional WS URL - allows for faster swap processing
#  #WS_URL: ""
#  #CLI - command line interface config
#  CLI_ADDRESS: "0.0.0.0"
#  CLI_PORT: 40130
#  #Maximum gas price
#  MAX_L1_FEE_GWEI: 20000000
#  MAX_L2_FEE_GWEI: 4000000
#  MAX_L1_DATA_FEE_GWEI: 10000000
#  #Starknet chain to use
#  CHAIN: "SEPOLIA"
#  #File with the wallet mnemonic seed
#  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

BOTANIX:
  #Botanix RPC URL, can either be an http or ws RPC
  RPC_URL: "https://node.botanixlabs.dev"
  #Maximum block range that the underlying RPC provider supports
  MAX_LOGS_BLOCK_RANGE: 900
  #CLI - command line interface config
  CLI_ADDRESS: "0.0.0.0"
  CLI_PORT: 40140
  #Fees
  MAX_FEE_GWEI: 2
  FEE_TIP_GWEI: 0.001
  #Botanix chain
  CHAIN: "TESTNET"

  #File with wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

#Alpen RPC
ALPEN:
  #Alpen RPC URL, can either be an http or ws RPC
  RPC_URL: "https://rpc.testnet.alpenlabs.io"
  #Maximum block range that the underlying RPC provider supports
  MAX_LOGS_BLOCK_RANGE: 900
  #CLI - command line interface config
  CLI_ADDRESS: "0.0.0.0"
  CLI_PORT: 40160
  #Fees
  MAX_FEE_GWEI: 2
  FEE_TIP_GWEI: 0.001
  #Alpen chain
  CHAIN: "TESTNET"

  #File with wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
