#Bitcoin RPC configuration
BTC_PROTOCOL: "http"
BTC_PORT: 18332
ZMQ_PORT: 49332
BTC_HOST: "bitcoind-testnet4"
BTC_RPC_USERNAME: "user1"
BTC_RPC_PASSWORD: "ThisIsAPassword"
BTC_NETWORK: "testnet4"

NOSTR_RELAYS: ["wss://relay.damus.io", "wss://nostr.einundzwanzig.space", "wss://relay01.lnfi.network/", "wss://njump.me/", "wss://fiatjaf.com/"]

#Enable/disable individual watchtowers
WATCHTOWERS:
  LEGACY_SWAPS: true
  SPV_SWAPS: true
  HTLC_SWAPS: true

#CLI - command line interface config
CLI_ADDRESS: "0.0.0.0"
CLI_PORT: 40120

#GOAT Network RPC
GOAT:
  #Alpen RPC URL, can either be an http or ws RPC
  RPC_URL: "https://rpc.testnet3.goat.network"
  #Maximum block range that the underlying RPC provider supports
  MAX_LOGS_BLOCK_RANGE: 900
  #Fees
  MAX_FEE_GWEI: 2
  #Has to be at least 0.005 for GOAT Network!
  FEE_TIP_GWEI: 0.005
  #GOAT chain
  CHAIN: "TESTNET4"

  #File with wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
